### ISSUE TITLE
Mod will cause desyncs in MP

### ISSUE THREAD

**Issue by Nexela** [lf-/slowkey#1]
Need to use the global.table to save the state, (preferably indexed by user)

**Comment by lf-** [comment]
Odd. I was using it with my friend and had no such issues.

**Comment by Nexela** [comment]
Using / changing / recalling variables that are not saved to the global table can cause this error. 

Load up your game. enable the slow mode, have your friend connect, He will either desync on entrance or desync after you toggle slow mode off.

Also the variable should be saved in such a way that it only affects the player that toggled it.  In fact give me a few minutes
